### ISSUE TITLE
Failure on TASK [fubarhouse.golang : Go-Lang | Moving to installation directory]

### ISSUE THREAD

**Issue by markdorison** [fubarhouse/ansible-role-golang#66]
This role has worked for me in the past but I am now encountering the following error on the "Moving to installation directory" task. I redacted the information about the box it is running on.

`fatal: [FQDN_REDACTED -> IP_REDACTED]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/tmp/go/\" \"IP_REDACTED:/root/go\"", "failed": true, "msg": "Warning: Permanently added 'IP_REDACTED' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]\n", "rc": 255}`

**Comment by fubarhouse** [comment]
@markdorison first of all thanks for submitting a ticket!

Second, as you're getting the following: `Permission denied (publickey)`, could you please check the ssh-agent to ensure keys have been added?

You can use the following
````
echo $SSH_AGENT_PID
eval $(ssh-add)
ssh-add
ssh-add -l
````

This will rule out any obvious errors. I am intending on going back through this role again for a new release - much like what I've just completed for my curl role.

**Comment by ctorgalson** [comment]
@fubarhouse: Thanks!

(I work with @markdorison and it was me who ran into this issue). The machine the Ansible playbook was running from does have a passphrase-protected ssh-key to the remote machine, but we know it was `ssh-add`ed because the playbook was able to connect to the remote machine at all (and successfully complete all tasks up to the golang role).

But reading through the code, it looks like it's the `ansible_ssh_user is undefined` that's even forcing the role's use of `synchronize` instead of `shell`, and this playbook is usually run without `-u`, and I don't think we'd found [the `fubarhouse_user` variable](https://github.com/fubarhouse/ansible-role-golang/blob/master/tasks/setup.yml#L7).

I'll run the playbook again at a quiet time with a value for `user` or `fubarhouse_user` to see if that's the issue & report back.

**Comment by fubarhouse** [comment]
@ctorgalson that actually describes something I can diagnose much better, so I'll look into this for you and respond.

Under no circumstance should `fubarhouse_user` not be assigned a value, but at least now I know there is a case where it may not be.

Are you able to provide any given reason the following two tasks would be skipped?

````
- name: "Go-Lang | Define user variable for ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined and fubarhouse_user is not defined

- name: "Go-Lang | Define user variable for non-ssh use"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined and fubarhouse_user is not defined
````
