### ISSUE TITLE
go1.10beta1 fails to install from source.

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/ansible-role-golang#77]
````
TASK [fubarhouse.golang : Go-Lang | Verify version] ***************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/local/go/bin/go version", "delta": "0:00:00.050800", "end": "2018-01-11 21:49:46.362911", "failed_when_result": true, "rc": 0, "start": "2018-01-11 21:49:46.312111", "stderr": "", "stderr_lines": [], "stdout": "go version devel +9ce6b5c2ed Thu Dec 7 17:38:51 2017 +0000 darwin/amd64", "stdout_lines": ["go version devel +9ce6b5c2ed Thu Dec 7 17:38:51 2017 +0000 darwin/amd64"]}
````
Playbook, for help in diagnosis
````
---

- hosts: localhost
  vars:
    go_version: 1.10beta1
    build_go_from_source: true
    install_go_bootstrap: true

  roles:
    - fubarhouse.golang
````

So, obviously source builds from git should have a different set of verification conditions.
